apiVersion: v1
kind: Service
metadata:
  name: api-doc-service
spec:
  selector:
    app: api-doc
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: streamlit-demo-app
spec:
  to:
    kind: Service
    name: streamlit-demo-app
  port:
    targetPort: 8501
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
